blank_issues_enabled: true
contact_links:
  - name: "ğŸ›ï¸ Problem with the marketplace?"
    url: https://learn.microsoft.com/en-us/azure/devops/marketplace/install-extension?view=azure-devops&tabs=browser#frequently-asked-questions-faqs
    about: In case you need support for the Azure DevOps Marketplace. 
  - name: "ğŸ§‘â€ğŸ’» Problem with tfx"
    url: https://github.com/microsoft/tfs-cli/issues
    about: For reporting issues with `tfx`.
  - name: "â™¾ï¸ Problem with Azure DevOps"
    url: https://developercommunity.visualstudio.com/AzureDevOps
    about: For reporting issues with `Azure DevOps`.
